
package muhich_indivproject;

/**
 * JFrame of an individual nostalgia's information. The user can modify or delete this entry
 * @author Alex Jerard Muhich
 */
public class IndivNostalgiaFrame extends javax.swing.JFrame {
    private static Nostalgia nost;
    private final SQLiteJDBC database;
    /**
     * Creates new form IndivNostalgiaFrame
     * @param nost
     */
    public IndivNostalgiaFrame(Nostalgia nost) {
        IndivNostalgiaFrame.nost = nost;
        initComponents();
        //display the nost's information
        etTitleNost.setText(nost.getTitle());
        etAuthorNost.setText(nost.getAuthor());
        etYearNost.setText(nost.getYear());
        etOwnNost.setText(nost.getOwnership());
        
        database = new SQLiteJDBC();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        etTitleNost = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        etAuthorNost = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        etYearNost = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        etOwnNost = new javax.swing.JTextField();
        btnDeleteNost = new javax.swing.JButton();
        btnModifyNost = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Nostalgia");
        setResizable(false);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Title:");

        etTitleNost.setEditable(false);
        etTitleNost.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        etTitleNost.setText("Old Bookey McBookFace");

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Author:");

        etAuthorNost.setEditable(false);
        etAuthorNost.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        etAuthorNost.setText("Authorey McAuthorFace");

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Year of Publication:");

        etYearNost.setEditable(false);
        etYearNost.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        etYearNost.setText("1900");

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Do I Own This?");

        etOwnNost.setEditable(false);
        etOwnNost.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        etOwnNost.setText("Yes");

        btnDeleteNost.setText("Delete");
        btnDeleteNost.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteNostActionPerformed(evt);
            }
        });

        btnModifyNost.setText("Modify");
        btnModifyNost.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModifyNostActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(etOwnNost)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(etYearNost)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(etTitleNost, javax.swing.GroupLayout.DEFAULT_SIZE, 266, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(etAuthorNost, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnModifyNost)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnDeleteNost)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(etTitleNost, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(etAuthorNost, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(etYearNost, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(etOwnNost, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDeleteNost)
                    .addComponent(btnModifyNost))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    /**
     * Deletes this book from the database and closes it's window.
     * @param evt 
     */
    private void btnDeleteNostActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteNostActionPerformed
        database.delete(etTitleNost.getText(), etAuthorNost.getText(), etOwnNost.getText(),
                null, null, etYearNost.getText());
        this.dispose();
    }//GEN-LAST:event_btnDeleteNostActionPerformed
    /**
     * If modify is clicked, it allows the data to be edited and then the user can save
     * the data, if the user X's out before saving, the data won't be changed.
     * @param evt 
     */
    private void btnModifyNostActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModifyNostActionPerformed
        if(btnModifyNost.getText().equals("Save")){
            database.updateBook(null, nost.getTitle(), nost.getAuthor(), nost.getOwnership(),
                    nost.getYear(), null, etTitleNost.getText(), etAuthorNost.getText(), null,
                    etOwnNost.getText(), etYearNost.getText());
            //set the text fields to be uneditable
            etAuthorNost.setEditable(false);
            etOwnNost.setEditable(false);
            etTitleNost.setEditable(false);
            etYearNost.setEditable(false);
        }
        //Modify
        else{
            //allow the text fields to be editable
            etAuthorNost.setEditable(true);
            etOwnNost.setEditable(true);
            etTitleNost.setEditable(true);
            etYearNost.setEditable(true);
            //change the button text to save
            btnModifyNost.setText("Save");
        }
    }//GEN-LAST:event_btnModifyNostActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IndivNostalgiaFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new IndivNostalgiaFrame(nost).setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDeleteNost;
    private javax.swing.JButton btnModifyNost;
    private javax.swing.JTextField etAuthorNost;
    private javax.swing.JTextField etOwnNost;
    private javax.swing.JTextField etTitleNost;
    private javax.swing.JTextField etYearNost;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables
}
