package muhich_indivproject;

/**
 * JFrame of an individual book's information. The user can modify or delete this entry
 * @author Alex Jerard Muhich
 */
public class IndivBookFrame extends javax.swing.JFrame {
    private Book book; //helper variable to remember old info when modifying the entry
    /**
     * Creates new form IndivBookFrame
     * @param book
     */
    public IndivBookFrame(Book book) {
        this.book = book;
        initComponents();
        etTitleBook.setText(book.getTitle());
        etAuthorBook.setText(book.getAuthor());
        etOwnBook.setText(book.getOwnership());
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titleLabelBook = new javax.swing.JLabel();
        etTitleBook = new javax.swing.JTextField();
        authorLabelBook = new javax.swing.JLabel();
        etAuthorBook = new javax.swing.JTextField();
        ownLabelBook = new javax.swing.JLabel();
        etOwnBook = new javax.swing.JTextField();
        btnDeleteBook = new javax.swing.JButton();
        btnModifyBook = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Book");
        setResizable(false);

        titleLabelBook.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleLabelBook.setText("Title:");

        etTitleBook.setEditable(false);
        etTitleBook.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        etTitleBook.setText("Bookey McBookFace");

        authorLabelBook.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        authorLabelBook.setText("Author:");

        etAuthorBook.setEditable(false);
        etAuthorBook.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        etAuthorBook.setText("Authorey McAuthorFace");

        ownLabelBook.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ownLabelBook.setText("Do I Own This?");

        etOwnBook.setEditable(false);
        etOwnBook.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        etOwnBook.setText("Yes");

        btnDeleteBook.setText("Delete");
        btnDeleteBook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteBookActionPerformed(evt);
            }
        });

        btnModifyBook.setText("Modify");
        btnModifyBook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModifyBookActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(etOwnBook)
                    .addComponent(etAuthorBook, javax.swing.GroupLayout.DEFAULT_SIZE, 229, Short.MAX_VALUE)
                    .addComponent(etTitleBook, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(titleLabelBook, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(authorLabelBook, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ownLabelBook, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnModifyBook)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnDeleteBook)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(titleLabelBook)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(etTitleBook, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(authorLabelBook)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(etAuthorBook, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ownLabelBook)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(etOwnBook, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDeleteBook)
                    .addComponent(btnModifyBook))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    /**
     * Deletes this book from the database and closes it's window.
     * @param evt 
     */
    private void btnDeleteBookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteBookActionPerformed
        SQLiteJDBC database = new SQLiteJDBC();
        database.delete(etTitleBook.getText(), etAuthorBook.getText(), etOwnBook.getText(),
                null, null, null);
        this.dispose();
    }//GEN-LAST:event_btnDeleteBookActionPerformed
    /**
     * If modify is clicked, it allows the data to be edited and then the user can save
     * the data, if the user X's out before saving, the data won't be changed.
     * @param evt 
     */
    private void btnModifyBookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModifyBookActionPerformed
        if(btnModifyBook.getText().equals("Save")){
            SQLiteJDBC database = new SQLiteJDBC();
            database.updateBook(null, book.getTitle(), book.getAuthor(), book.getOwnership(),
                    null, null, etTitleBook.getText(), etAuthorBook.getText(), null,
                    etOwnBook.getText(), null);
            //set the text fields to be uneditable
            etAuthorBook.setEditable(false);
            etOwnBook.setEditable(false);
            etTitleBook.setEditable(false);
        }
        //Modify
        else{
            //allow the text fields to be editable
            etAuthorBook.setEditable(true);
            etOwnBook.setEditable(true);
            etTitleBook.setEditable(true);
            //change the button text to save
            btnModifyBook.setText("Save");
        }
    }//GEN-LAST:event_btnModifyBookActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IndivBookFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IndivBookFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IndivBookFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IndivBookFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new IndivBookFrame(new Book(null, null, null)).setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel authorLabelBook;
    private javax.swing.JButton btnDeleteBook;
    private javax.swing.JButton btnModifyBook;
    private javax.swing.JTextField etAuthorBook;
    private javax.swing.JTextField etOwnBook;
    private javax.swing.JTextField etTitleBook;
    private javax.swing.JLabel ownLabelBook;
    private javax.swing.JLabel titleLabelBook;
    // End of variables declaration//GEN-END:variables
}
