
package muhich_indivproject;

/**
 *
 * @author Alex Jerard Muhich
 */
public class IndivMangaFrame extends javax.swing.JFrame {
    private Manga manga;
    /**
     * Creates new form IndivMangaFrame
     * @param manga
     */
    public IndivMangaFrame(Manga manga) {
        this.manga = manga;
        initComponents();
        etISBN1.setText(manga.getIsbn());
        etTitle1.setText(manga.getTitle());
        etAuthor1.setText(manga.getAuthor());
        etVolume1.setText(manga.getVolume());
        etOwn1.setText(manga.getOwnership());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        etISBN1 = new javax.swing.JTextField();
        etTitle1 = new javax.swing.JTextField();
        etAuthor1 = new javax.swing.JTextField();
        etVolume1 = new javax.swing.JTextField();
        etOwn1 = new javax.swing.JTextField();
        btnDeleteManga = new javax.swing.JButton();
        ownLabel1 = new javax.swing.JLabel();
        volumeLabel1 = new javax.swing.JLabel();
        authorLabel1 = new javax.swing.JLabel();
        titleLabel1 = new javax.swing.JLabel();
        isbnLabel1 = new javax.swing.JLabel();
        btnModifyManga = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Manga");
        setResizable(false);

        etISBN1.setEditable(false);
        etISBN1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        etISBN1.setText("9781234567890");

        etTitle1.setEditable(false);
        etTitle1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        etTitle1.setText("Dummy Manga Title");

        etAuthor1.setEditable(false);
        etAuthor1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        etAuthor1.setText("Author McAuthorstein");

        etVolume1.setEditable(false);
        etVolume1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        etVolume1.setText("5");

        etOwn1.setEditable(false);
        etOwn1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        etOwn1.setText("Yes");

        btnDeleteManga.setText("Delete");
        btnDeleteManga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteMangaActionPerformed(evt);
            }
        });

        ownLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ownLabel1.setText("Do I Own This?");

        volumeLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        volumeLabel1.setText("Volume #");

        authorLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        authorLabel1.setText("Author");

        titleLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleLabel1.setText("Title");

        isbnLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        isbnLabel1.setText("ISBN");

        btnModifyManga.setText("Modify");
        btnModifyManga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModifyMangaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ownLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(etISBN1)
                    .addComponent(etTitle1)
                    .addComponent(etAuthor1, javax.swing.GroupLayout.DEFAULT_SIZE, 259, Short.MAX_VALUE)
                    .addComponent(etVolume1)
                    .addComponent(etOwn1)
                    .addComponent(volumeLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(authorLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(titleLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(isbnLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnModifyManga)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnDeleteManga, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(isbnLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(etISBN1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(titleLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(etTitle1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(authorLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(etAuthor1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(volumeLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(etVolume1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ownLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(etOwn1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDeleteManga)
                    .addComponent(btnModifyManga))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Allows the user to modify/save the values for the manga
     * @param evt 
     */
    private void btnDeleteMangaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteMangaActionPerformed
        SQLiteJDBC database = new SQLiteJDBC();
        database.delete(etTitle1.getText(), etAuthor1.getText(), etOwn1.getText(),
                etISBN1.getText(), etVolume1.getText(), null);
        this.dispose();
    }//GEN-LAST:event_btnDeleteMangaActionPerformed
    /**
     * 
     * @param evt 
     */
    private void btnModifyMangaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModifyMangaActionPerformed
        if(btnModifyManga.getText().equals("Save")){
            SQLiteJDBC database = new SQLiteJDBC();
            database.updateBook(manga.getIsbn(), manga.getTitle(), manga.getAuthor(), manga.getOwnership(),
                    null, etISBN1.getText(), etTitle1.getText(), etAuthor1.getText(), etVolume1.getText(),
                    etOwn1.getText(), null);
            //set the text fields to be uneditable
            etAuthor1.setEditable(false);
            etOwn1.setEditable(false);
            etTitle1.setEditable(false);
            etVolume1.setEditable(false);
            etISBN1.setEditable(false);
        }
        //Modify
        else{
            //allow the text fields to be editable
            etAuthor1.setEditable(true);
            etOwn1.setEditable(true);
            etTitle1.setEditable(true);
            etVolume1.setEditable(true);
            etISBN1.setEditable(true);
            //change the button text to save
            btnModifyManga.setText("Save");
        }
    }//GEN-LAST:event_btnModifyMangaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException |
                 InstantiationException |
                 IllegalAccessException | 
                 javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IndivMangaFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new IndivMangaFrame(new Manga(null, null, null, null, null)).setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel authorLabel1;
    private javax.swing.JButton btnDeleteManga;
    private javax.swing.JButton btnModifyManga;
    private javax.swing.JTextField etAuthor1;
    private javax.swing.JTextField etISBN1;
    private javax.swing.JTextField etOwn1;
    private javax.swing.JTextField etTitle1;
    private javax.swing.JTextField etVolume1;
    private javax.swing.JLabel isbnLabel1;
    private javax.swing.JLabel ownLabel1;
    private javax.swing.JLabel titleLabel1;
    private javax.swing.JLabel volumeLabel1;
    // End of variables declaration//GEN-END:variables
}
